### PR TITLE
Factor out common methods on Date

### PR DESCRIPTION
**Pull request by mehrdad-shokri**
Since both Jalali and Gregorian have this method and I instantiate both in ``Date`` field, I would like to add this method to Date class.

### CODE REVIEW

**Comment by mehrdad-shokri** [comment]
@FatulM are you considering this?

**Comment by FatulM** [comment]
Hi mehrdad,
I will speak with you within a few days ...
Please remind me ☺️
@mehrdad-shokri

**Comment by mehrdad-shokri** [comment]
Alright😀

**Comment by FatulM** [comment]
There was a reason for not including common methods on date object when I was developing the first versions of library ...
What I remember is that, the day, month and year perform differently on different calendar systems ...
May be we are in a leap year in jalali and not in a leap year in miladi ...
At first I wanted to include Qamari calendar system which would make this issue far more complicated ...

**Comment by FatulM** [comment]
The main problem is that a person would have a date object and not knowing that it is a jalali or miladi
And assume that for example this is a jalali date, but it is a miladi date
And change its month to month one، assuming it will go to farvardin which is 31 days but actually it will go to a miladi month with lower length and this may cause problems if for example we are in day 31

**Comment by FatulM** [comment]
So by not including most of the methods in date super class I will force user to change change the date either to jalali or miladi and perform actions
If I wanted to comply to my procedure completely I shouldn't include year, month and ... Getters in date class too
I think by this convention the only safe method is toDateTime()

**Comment by FatulM** [comment]
This a strategic library for persian flutter ecosystem 😅
So I should be completely sure before changing it's public API

**Comment by FatulM** [comment]
But I have an idea, That is you 
1 include all common methods in date class
2 add `@ovveride` to all methods of jalali and Gregorian methods which you included
3 add *both* toJalai and toGregorian to Date class, and implement toJalai on Jalali to return this and toGregorian on Gregorian to return this, and add a one line documentation for it
4 add tests for toJalali for Jalali class checking that will return a same value and toGregorian for Gregorian
5 update version to  v0.11.0-nullsafety.0
6 update readme that toJalali on Jalali will return same and no performance overhead and like for toGregorian
7 add Dart docs for common methods on Date class
8 make sure your nullsafety is on and using latest beta flutter and calling Dart pub update on project not flutter pub update

**Comment by FatulM** [comment]
What is your opinion ?
@mehrdad-shokri

**Comment by mehrdad-shokri** [comment]
Hi I will get back to you after a while

**Comment by mehrdad-shokri** [comment]
Hello @FatulM hope you're doing well. So about your concern I would say this is an OOP concept. Date is an abstract class so you would declare your variable as ``Date`` type(but won't be able to initialize it) It will look something like this:  
`Date myDate = getDate(calendarSystem); // getDate returns either Jalali or Gregorian depending on calendarSystem `  
So now the user can call addYears, addMonths, etc on ``myDate`` without worrying about it's type.  
whatever date type ``myDate`` is, it will work properly(assuming the user instantiated the correct date type)  
About your proposition, I completely agree with it except for adding ``toJalali`` and ``toGregorian`` to the Date class.  
Since it will create a cyclic dependency between classes. Also, it would require us to modify the abstract class whenever adding another implementation of this class which I don't think is a good practice ( concrete implementations are supposed to depend on abstract class, not the other way around)

**Comment by FatulM** [comment]
Ok, I agree with you.
I will merge this as soon as I have time ...
Thanks for your contribution.
@mehrdad-shokri

**Comment by FatulM** [comment]
But it will take some time until I have time to do all of changes and publish a new version.
And I think adding new features to legacy (non nullsafe) branch is not needed.
And I agree with you about to*() methods.

**Comment by mehrdad-shokri** [comment]
alright thanks. I will update my pr to cover your requirements if I make time.

**Review by FatulM — APPROVED** [review]
I'll add the rest …

**Comment by FatulM** [comment]
thanks 😄 
@mehrdad-shokri

**Pull request merged**
